### ISSUE TITLE
作者，你好，请教一下

### ISSUE THREAD

**Issue by wellcao** [wangyeming/FibonacciList#1]
楼主，不知道在不在线？最近也刚刚收到这样的笔试题（已经杯具），看来课程格子用这个题难为了很多很多面试者了。尝试着运行了一下你的代码，觉得已经满足要求了。不知道你当时是否通过了笔试，感觉2个小时内完成这样的要求太困难了（感觉周围的一些做Android的同事都没有这样的功底啊），是不是我太渣了

**Comment by wangyeming** [comment]
@wellcao 你好，我不太清楚你现在的状况，姑且推测你应该是刚毕业，自学安卓，想找一个安卓开发的工作是吗？这个项目是我两年前刚来北京时，面试课程格子时的笔试题，他们收到简历会邮件发送面试题，要求面试前完成。我不是科班出身，也错过一切校招的机会，只是自学了一段时间的安卓，来北京找工作了，所以可能也能理解你的处境。

其实对于刚来北京没有工作经验的我，面试方提前发送邮件，出一个不算复杂不算特别水的题目，其实我还是挺高兴的。比起对面试官要问得题目一无所知，提前给了题目，至少知道面试方希望考察的知识点在哪里，题目可以私下准备，面试的时候也可以针对性的聊一聊是解决题目的思路。比如说这一题，出题方希望考察的知识点包括但不限于：

* 新建一个安卓项目
* 列表数据的展示，分页加载，列表数据的正序和反序展示
* 后台处理数据计算，通知前台ui刷新
* 斐波那契数的高效算法

由于这个项目写得比较久了，当初自学的基础也比较差，所以代码也有不少问题，比如，后台计算我直接new一个线程，而不是通过线程池或者handler等工具来处理异步任务，是不合适的。

第一个知识点没什么说的，第二个ListView或者RecyclerView的使用，算是安卓中的基础中的基础，正序反序切换只是调用系统api而已，不会的话网上一大堆博文可以参考，分页加载也是一样，我这里采用的是最基础的滑动监听，也不难。

第三个知识点，用的也非常多，其实考察的是，安卓的ui线程不建议做复杂的耗时的操作，通过一些异步的工具(建议使用Handler)，后台线程计算，通知前台ui刷新，具体的可以找一些博文，写点例子练练手。

第四个可能相对来说比较难，我个人觉得，面试官可能希望考察的是，写题目的人**解决问题的思路**。斐波那契数的计算，根据公式，自己通过java实现一个最基础的函数，这很简单。但就题目的要求而言，这样的计算速度是不能接受的，要明确一点，这些基础的算法，网上一大堆现成的方案，从各种算法的效率比较到最终的代码实现，你完全可以先复制粘贴，然后再去理解。遇到这种题目，面试官又让你私下完成，显然你是可以通过搜索引擎，找到一个最合适的算法，甚至就是java实现的现成的代码，用到题目里。不过我们可以完成题目后，再看一看算法的实现原理(包括数学上，它用了一个怎么的公式)，java上如果处理这种位数很多的数字（BigInteger），出现的基础的位运算是怎么一回事(如果你和我一样没有计算机基础的话)

写了这么多，希望你能有所收获。给几个小建议：
1. 从头到尾自学下安卓的官方教程(http://hukai.me/android-training-course-in-chinese/index.html)，然后可以买一本基础的书籍，系统的学习一下。（不建议买疯狂安卓，讲的太细不咋样）《 android群英传》不错，可以作为入门书籍。

2. java的话，一定要对着一本书，从头到尾把java的基础知识点过一遍，《java编程思想》不错，java的书大部头挺多，这个我也没什么好办法，当初我学的时候也挺痛苦，这个要咬咬牙挺过去

3. 设计模式要稍微了解下，面试官很多喜欢问这些问题，确实工作中用到了也很多，我觉得讲的最好的书是这本 《Android 源码设计模式解析与实战》

如果你要面试的话，无论如何，第一点一定要做到。

**Comment by wellcao** [comment]
其实你误解我意思了，单纯的一个下拉刷新上拉加载的滑动列表再简单不过，
我是没有网上查资料写的，我不太熟悉的是bigdecimal类，不过查看一下源代码就知道了，我没有做出的f（n）到f（n^2）的转换，高中数列相关的都忘了

2017年1月23日 10:45，"王烨明" <notifications@github.com>写道：
